/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.marviemiranda1;

import javax.swing.JOptionPane;

/**
 *
 * @author CL2~PC12
 */
public class Cafeteria extends javax.swing.JFrame {

    /**
     * Creates new form Cafeteria
     */
    public Cafeteria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtorder = new javax.swing.JTextField();
        btnorder = new javax.swing.JButton();
        txtquan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtcash = new javax.swing.JTextField();
        txtchange = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        txtprodname = new javax.swing.JTextField();
        txtconquan = new javax.swing.JTextField();
        txttype = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        txtvat = new javax.swing.JTextField();
        txttotvat = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txttotalre = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 48)); // NOI18N
        jLabel1.setText("Menu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Snacks");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Drinks");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));
        getContentPane().add(txtorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 130, 40));

        btnorder.setText("Enter");
        btnorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnorderActionPerformed(evt);
            }
        });
        getContentPane().add(btnorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, -1, -1));
        getContentPane().add(txtquan, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 130, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel4.setText("Cafeteria");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 260, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("[1] Piatot -  15 petot");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("[2] Nova - 15 petot");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("[6] Wata -10 petot");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("[7] Coke - 20 petot");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Order:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Quantity:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));
        getContentPane().add(txtcash, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 130, 40));

        txtchange.setEnabled(false);
        getContentPane().add(txtchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 130, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("Cash:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("Change:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("[3] V-cut - 15");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel15.setText("CALCULATION");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, -1, -1));

        txtprice.setEnabled(false);
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, 120, -1));

        txtprodname.setEnabled(false);
        getContentPane().add(txtprodname, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 120, -1));

        txtconquan.setEnabled(false);
        getContentPane().add(txtconquan, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 120, -1));

        txttype.setEnabled(false);
        getContentPane().add(txttype, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 120, -1));

        txttotal.setEnabled(false);
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 120, -1));

        txtvat.setEnabled(false);
        getContentPane().add(txtvat, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, 120, -1));

        txttotvat.setEnabled(false);
        getContentPane().add(txttotvat, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, 120, -1));

        jLabel16.setText("Product:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, -1, -1));

        jLabel17.setText("Quantity:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, -1, -1));

        jLabel13.setText("Price:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, -1, -1));

        jLabel18.setText("Total:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, -1, -1));

        jLabel19.setText("Vat");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, -1, -1));

        jLabel20.setText("Total Vat");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, -1, -1));

        txttotalre.setEnabled(false);
        getContentPane().add(txttotalre, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 120, -1));

        jLabel21.setText("Change:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnorderActionPerformed

            int choice = Integer.parseInt(txtorder.getText());
            int quantity = Integer.parseInt(txtquan.getText());

            int prod_price = 0;
            double vat = 0.12;

            
            if (choice == 1){
                JOptionPane.showMessageDialog(null , "You choose Piatot", "Cafeteria", JOptionPane.INFORMATION_MESSAGE);
                txtprodname.setText("Piatot");
                txtprice.setText("15");
                txttype.setText("Snack");
                txtconquan.setText("" +  txtconquan);
                
            }
            else if (choice == 2){
            JOptionPane.showMessageDialog(null , "You choose Nova", "Cafeteria", JOptionPane.INFORMATION_MESSAGE);
                txtprodname.setText("Nova");
                txtprice.setText("15");
                txttype.setText("Snack");
            }
            else if (choice == 3){
            JOptionPane.showMessageDialog(null , "You choose V-cut", "Cafeteria", JOptionPane.INFORMATION_MESSAGE);
                txtprodname.setText("V-cut");
                txtprice.setText("15");
                txttype.setText("Snack");
            }
            else if (choice == 4){
            JOptionPane.showMessageDialog(null , "You choose Wata", "Cafeteria", JOptionPane.INFORMATION_MESSAGE);
                txtprodname.setText("Wata");
                txtprice.setText("10");
                txttype.setText("Drinks");
            }
            else if (choice != 5) {
                JOptionPane.showMessageDialog(null , "You choose Coke", "Cafeteria", JOptionPane.INFORMATION_MESSAGE);
                txtprodname.setText("Coke");
                txtprice.setText("20");
                txttype.setText("Drinks");
            } else {
                JOptionPane.showMessageDialog(null, "Order Success","",JOptionPane.INFORMATION_MESSAGE);
            }
            int total = prod_price * quantity;
            double vatAmount = total * vat;
            double totalWithVat = total + vatAmount;
            
            txtvat.setText("" + vatAmount);
            txttotvat.setText("" + totalWithVat);
            
            int cash = Integer.parseInt(txttotal.getText());
            double change = cash - totalWithVat;
            txttotalre.setText("" + change);
            
            JOptionPane.showConfirmDialog(null , "Complete", "Confirmation ", JOptionPane.YES_NO_CANCEL_OPTION);
            
             
                
        
    }//GEN-LAST:event_btnorderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cafeteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cafeteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cafeteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cafeteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cafeteria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnorder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtcash;
    private javax.swing.JTextField txtchange;
    private javax.swing.JTextField txtconquan;
    private javax.swing.JTextField txtorder;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtprodname;
    private javax.swing.JTextField txtquan;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txttotalre;
    private javax.swing.JTextField txttotvat;
    private javax.swing.JTextField txttype;
    private javax.swing.JTextField txtvat;
    // End of variables declaration//GEN-END:variables
}
