/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.marviemiranda1;

import javax.swing.JOptionPane;

/**
 *
 * @author CL2~PC12
 */
public class EliMabaho extends javax.swing.JFrame {

    /**
     * Creates new form EliMabaho
     */
    public EliMabaho() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtfSdoghot = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtfSwata = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtfchoices = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtfquantity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtfprice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtfcash = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtftotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("[1] SNACKS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel2.setText("[2] DRINKS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("STOCKS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, -1));

        jLabel4.setText("Doghot");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, -1));

        txtfSdoghot.setEnabled(false);
        getContentPane().add(txtfSdoghot, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));

        jLabel5.setText("Wata");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        txtfSwata.setEnabled(false);
        getContentPane().add(txtfSwata, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));

        jLabel6.setText("Choices");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));
        getContentPane().add(txtfchoices, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 100, -1));

        jLabel7.setText("Quantity");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));
        getContentPane().add(txtfquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 100, -1));

        jLabel8.setText("Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        txtfname.setEnabled(false);
        getContentPane().add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 100, -1));

        jLabel9.setText("Price");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        txtfprice.setEnabled(false);
        getContentPane().add(txtfprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 100, -1));

        jButton1.setText("Compute");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, -1, -1));

        jLabel10.setText("Cash");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));
        getContentPane().add(txtfcash, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 100, -1));

        jLabel11.setText("Total");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        txtftotal.setEnabled(false);
        getContentPane().add(txtftotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            int choice = Integer.parseInt(txtfname.getText());
            int quantity = Integer.parseInt(txtfquantity.getText());

            
            
            

            int prod_price = 0;
            double vat = 0.12;
            
            
            if (choice == 1){
            JOptionPane.showMessageDialog(null, "You choose Snacks", "Cafeteria", JOptionPane.INFORMATION_MESSAGE);
                txtfname.setText("Doghot");
                txtfprice.setText("15");
                txtfSdoghot.setText("" + txtfSdoghot);
                txtftotal.setText("" + txtftotal);
  
            }
                        if (choice == 2){
            JOptionPane.showMessageDialog(null, "You choose Drinks", "Cafeteria", JOptionPane.INFORMATION_MESSAGE);
                txtfname.setText("Wata");
                txtfprice.setText("15");
                txtfSwata.setText("" + txtfSwata);
                txtftotal.setText("" + txtftotal);
  
            }
                        else {
                        JOptionPane.showMessageDialog(null, "Order Success","",JOptionPane.INFORMATION_MESSAGE);
            }
            int total = prod_price * quantity;
            double vatAmount = total * vat;
            double totalWithVat = total + vatAmount;
                
            int cash = Integer.parseInt(txtftotal.getText());
            double change = cash - totalWithVat; 
            
                        
            JOptionPane.showConfirmDialog(null , "Complete", "Confirmation ", JOptionPane.YES_NO_CANCEL_OPTION);            
                        
            
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliMabaho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliMabaho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliMabaho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliMabaho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliMabaho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtfSdoghot;
    private javax.swing.JTextField txtfSwata;
    private javax.swing.JTextField txtfcash;
    private javax.swing.JTextField txtfchoices;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtfprice;
    private javax.swing.JTextField txtfquantity;
    private javax.swing.JTextField txtftotal;
    // End of variables declaration//GEN-END:variables
}
